version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: jobpulse_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: jobpulse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - jobpulse_pgdata:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  jobpulse_pgdata:
